import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Book } from '../book/book.model';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  isHomeRoute: boolean = false;
  ismaintainRoute: boolean = false;
  isbookRoute: boolean = false;
  books: Book[] = [
    { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', price: 10.99, imageUrl: 'https://covers.openlibrary.org/b/id/10438377-L.jpg' },
    { title: '1984', author: 'George Orwell', price: 25.50, imageUrl: 'https://covers.openlibrary.org/b/id/10876479-L.jpg' },
    { title: 'To Kill a Mockingbird', author: 'Harper Lee', price: 15.75, imageUrl: 'https://covers.openlibrary.org/b/id/10569843-L.jpg' },
    { title: 'Pride and Prejudice', author: 'Jane Austen', price: 12.99, imageUrl: 'https://covers.openlibrary.org/b/id/8232140-L.jpg' },
    { title: 'The Catcher in the Rye', author: 'J.D. Salinger', price: 20.00, imageUrl: 'https://covers.openlibrary.org/b/id/10306035-L.jpg' },
    { title: 'The Hobbit', author: 'J.R.R. Tolkien', price: 14.95, imageUrl: 'https://covers.openlibrary.org/b/id/7695782-L.jpg' },
    { title: 'Moby Dick', author: 'Herman Melville', price: 18.75, imageUrl: 'https://covers.openlibrary.org/b/id/7225511-L.jpg' },
    { title: 'War and Peace', author: 'Leo Tolstoy', price: 22.50, imageUrl: 'https://covers.openlibrary.org/b/id/8224688-L.jpg' },
    { title: 'The Odyssey', author: 'Homer', price: 13.20, imageUrl: 'https://covers.openlibrary.org/b/id/10213776-L.jpg' },
    { title: 'Jane Eyre', author: 'Charlotte Brontë', price: 11.50, imageUrl: 'https://covers.openlibrary.org/b/id/7897692-L.jpg' },
    { title: 'Frankenstein', author: 'Mary Shelley', price: 16.00, imageUrl: 'https://covers.openlibrary.org/b/id/8224215-L.jpg' },
    { title: 'Dracula', author: 'Bram Stoker', price: 17.99, imageUrl: 'https://covers.openlibrary.org/b/id/8240197-L.jpg' },
    { title: 'The Picture of Dorian Gray', author: 'Oscar Wilde', price: 14.50, imageUrl: 'https://covers.openlibrary.org/b/id/8235204-L.jpg' },
    { title: 'Les Misérables', author: 'Victor Hugo', price: 19.75, imageUrl: 'https://covers.openlibrary.org/b/id/10443140-L.jpg' },
    { title: 'Little Women', author: 'Louisa May Alcott', price: 12.25, imageUrl: 'https://covers.openlibrary.org/b/id/10213799-L.jpg' },
    { title: 'Wuthering Heights', author: 'Emily Brontë', price: 15.00, imageUrl: 'https://covers.openlibrary.org/b/id/10318822-L.jpg' },
    { title: 'The Bell Jar', author: 'Sylvia Plath', price: 21.00, imageUrl: 'https://covers.openlibrary.org/b/id/8302380-L.jpg' },
    { title: 'Brave New World', author: 'Aldous Huxley', price: 18.20, imageUrl: 'https://covers.openlibrary.org/b/id/7291158-L.jpg' },
    { title: 'Catch-22', author: 'Joseph Heller', price: 24.00, imageUrl: 'https://covers.openlibrary.org/b/id/8258904-L.jpg' },
    { title: 'Slaughterhouse-Five', author: 'Kurt Vonnegut', price: 22.75, imageUrl: 'https://covers.openlibrary.org/b/id/8234360-L.jpg' },
    { title: 'Gone with the Wind', author: 'Margaret Mitchell', price: 27.00, imageUrl: 'https://covers.openlibrary.org/b/id/8229036-L.jpg' },
    { title: 'The Grapes of Wrath', author: 'John Steinbeck', price: 20.50, imageUrl: 'https://covers.openlibrary.org/b/id/7313834-L.jpg' },
    { title: 'The Lord of the Rings', author: 'J.R.R. Tolkien', price: 30.00, imageUrl: 'https://covers.openlibrary.org/b/id/8135311-L.jpg' },
    { title: 'A Tale of Two Cities', author: 'Charles Dickens', price: 16.75, imageUrl: 'https://covers.openlibrary.org/b/id/10526660-L.jpg' },
    { title: 'The Sun Also Rises', author: 'Ernest Hemingway', price: 19.25, imageUrl: 'https://covers.openlibrary.org/b/id/10353572-L.jpg' },
    { title: 'The Road', author: 'Cormac McCarthy', price: 23.50, imageUrl: 'https://covers.openlibrary.org/b/id/8270181-L.jpg' },
    { title: 'Middlesex', author: 'Jeffrey Eugenides', price: 18.99, imageUrl: 'https://covers.openlibrary.org/b/id/8543821-L.jpg' },
    { title: 'Never Let Me Go', author: 'Kazuo Ishiguro', price: 21.50, imageUrl: 'https://covers.openlibrary.org/b/id/8595837-L.jpg' },
    { title: 'The Handmaid\'s Tale', author: 'Margaret Atwood', price: 24.50, imageUrl: 'https://covers.openlibrary.org/b/id/8240684-L.jpg' },
    { title: 'The Kite Runner', author: 'Khaled Hosseini', price: 22.25, imageUrl: 'https://covers.openlibrary.org/b/id/7516701-L.jpg' },
    { title: 'Life of Pi', author: 'Yann Martel', price: 20.75, imageUrl: 'https://covers.openlibrary.org/b/id/8300541-L.jpg' },
    { title: 'The Book Thief', author: 'Markus Zusak', price: 19.00, imageUrl: 'https://covers.openlibrary.org/b/id/7804893-L.jpg' },
    { title: 'The Alchemist', author: 'Paulo Coelho', price: 17.50, imageUrl: 'https://covers.openlibrary.org/b/id/8293466-L.jpg' },
    { title: 'The Old Man and the Sea', author: 'Ernest Hemingway', price: 14.75, imageUrl: 'https://covers.openlibrary.org/b/id/7314473-L.jpg' },
    { title: 'The Secret History', author: 'Donna Tartt', price: 22.00, imageUrl: 'https://covers.openlibrary.org/b/id/10625153-L.jpg' },
    { title: 'The Outsiders', author: 'S.E. Hinton', price: 16.99, imageUrl: 'https://covers.openlibrary.org/b/id/8235297-L.jpg' },
    { title: 'The Lovely Bones', author: 'Alice Sebold', price: 18.75, imageUrl: 'https://covers.openlibrary.org/b/id/8261868-L.jpg' },
    { title: 'Big Little Lies', author: 'Liane Moriarty', price: 20.99, imageUrl: 'https://covers.openlibrary.org/b/id/8572965-L.jpg' },
    { title: 'The Giver', author: 'Lois Lowry', price: 12.50, imageUrl: 'https://covers.openlibrary.org/b/id/10757037-L.jpg' },
    { title: 'The Da Vinci Code', author: 'Dan Brown', price: 15.90, imageUrl: 'https://covers.openlibrary.org/b/id/8688977-L.jpg' },
    { title: 'The Shining', author: 'Stephen King', price: 18.00, imageUrl: 'https://covers.openlibrary.org/b/id/10778668-L.jpg' },
    { title: 'Harry Potter and the Sorcerer\'s Stone', author: 'J.K. Rowling', price: 29.95, imageUrl: 'https://covers.openlibrary.org/b/id/8083280-L.jpg' },
    { title: 'The Hunger Games', author: 'Suzanne Collins', price: 16.75, imageUrl: 'https://covers.openlibrary.org/b/id/7869302-L.jpg' },
    { title: 'Dune', author: 'Frank Herbert', price: 20.00, imageUrl: 'https://covers.openlibrary.org/b/id/8249351-L.jpg' },
    { title: 'The Martian', author: 'Andy Weir', price: 22.50, imageUrl: 'https://covers.openlibrary.org/b/id/8083166-L.jpg' },
    { title: 'Ready Player One', author: 'Ernest Cline', price: 21.25, imageUrl: 'https://covers.openlibrary.org/b/id/7911447-L.jpg' },
    { title: 'American Gods', author: 'Neil Gaiman', price: 23.00, imageUrl: 'https://covers.openlibrary.org/b/id/8245280-L.jpg' },
    { title: 'Neverwhere', author: 'Neil Gaiman', price: 18.50, imageUrl: 'https://covers.openlibrary.org/b/id/8228707-L.jpg' },
    { title: 'The Wind-Up Bird Chronicle', author: 'Haruki Murakami', price: 25.00, imageUrl: 'https://covers.openlibrary.org/b/id/7886815-L.jpg' },
    { title: 'The Goldfinch', author: 'Donna Tartt', price: 24.50, imageUrl: 'https://covers.openlibrary.org/b/id/8238325-L.jpg' },
    { title: 'The Girl with the Dragon Tattoo', author: 'Stieg Larsson', price: 17.99, imageUrl: 'https://covers.openlibrary.org/b/id/8272794-L.jpg' },
    { title: 'Shantaram', author: 'Gregory David Roberts', price: 22.75, imageUrl: 'https://covers.openlibrary.org/b/id/10717754-L.jpg' },
    { title: 'The Brief Wondrous Life of Oscar Wao', author: 'Junot Díaz', price: 21.50, imageUrl: 'https://covers.openlibrary.org/b/id/7887766-L.jpg' },
    { title: 'The Color Purple', author: 'Alice Walker', price: 15.25, imageUrl: 'https://covers.openlibrary.org/b/id/10568663-L.jpg' },
    { title: 'The Road', author: 'Cormac McCarthy', price: 22.00, imageUrl: 'https://covers.openlibrary.org/b/id/8270181-L.jpg' },
    { title: 'The Curious Incident of the Dog in the Night-Time', author: 'Mark Haddon', price: 18.99, imageUrl: 'https://covers.openlibrary.org/b/id/10439044-L.jpg' },
    { title: 'Gone Girl', author: 'Gillian Flynn', price: 23.50, imageUrl: 'https://covers.openlibrary.org/b/id/8688976-L.jpg' },
    { title: 'The Immortal Life of Henrietta Lacks', author: 'Rebecca Skloot', price: 19.00, imageUrl: 'https://covers.openlibrary.org/b/id/7907782-L.jpg' },
    { title: 'Educated', author: 'Tara Westover', price: 21.25, imageUrl: 'https://covers.openlibrary.org/b/id/10566560-L.jpg' },
    { title: 'Becoming', author: 'Michelle Obama', price: 22.00, imageUrl: 'https://covers.openlibrary.org/b/id/8277498-L.jpg' },
    { title: 'The Seven Husbands of Evelyn Hugo', author: 'Taylor Jenkins Reid', price: 17.75, imageUrl: 'https://covers.openlibrary.org/b/id/10701726-L.jpg' },
    { title: 'The Woman in the Window', author: 'A.J. Finn', price: 16.50, imageUrl: 'https://covers.openlibrary.org/b/id/10568768-L.jpg' },
    { title: 'The Girl on the Train', author: 'Paula Hawkins', price: 18.20, imageUrl: 'https://covers.openlibrary.org/b/id/10552713-L.jpg' },
    { title: 'Little Fires Everywhere', author: 'Celeste Ng', price: 19.75, imageUrl: 'https://covers.openlibrary.org/b/id/10493938-L.jpg' },
    { title: 'Where the Crawdads Sing', author: 'Delia Owens', price: 20.00, imageUrl: 'https://covers.openlibrary.org/b/id/10774539-L.jpg' },
    { title: 'Big Little Lies', author: 'Liane Moriarty', price: 18.50, imageUrl: 'https://covers.openlibrary.org/b/id/8572965-L.jpg' },
    { title: 'The Night Circus', author: 'Erin Morgenstern', price: 22.25, imageUrl: 'https://covers.openlibrary.org/b/id/8300628-L.jpg' },
    { title: 'The Casual Vacancy', author: 'J.K. Rowling', price: 20.75, imageUrl: 'https://covers.openlibrary.org/b/id/8273438-L.jpg' },
    { title: 'The Underground Railroad', author: 'Colson Whitehead', price: 21.75, imageUrl: 'https://covers.openlibrary.org/b/id/10722643-L.jpg' },
    { title: 'The Goldfinch', author: 'Donna Tartt', price: 23.00, imageUrl: 'https://covers.openlibrary.org/b/id/10529437-L.jpg' },
    { title: 'Circe', author: 'Madeline Miller', price: 24.50, imageUrl: 'https://covers.openlibrary.org/b/id/8236821-L.jpg' },
    { title: 'The Silent Patient', author: 'Alex Michaelides', price: 18.25, imageUrl: 'https://covers.openlibrary.org/b/id/10729079-L.jpg' },
    { title: 'Before We Were Strangers', author: 'Renée Carlino', price: 17.00, imageUrl: 'https://covers.openlibrary.org/b/id/10771173-L.jpg' },
    { title: 'The Tattooist of Auschwitz', author: 'Heather Morris', price: 19.50, imageUrl: 'https://covers.openlibrary.org/b/id/10727828-L.jpg' },
    { title: 'The Light We Lost', author: 'Jill Santopolo', price: 16.75, imageUrl: 'https://covers.openlibrary.org/b/id/10752856-L.jpg' },
    { title: 'The Paris Library', author: 'Janet Skeslien Charles', price: 18.50, imageUrl: 'https://covers.openlibrary.org/b/id/10727022-L.jpg' },
    { title: 'The Orphan Masters Son', author: 'Adam Johnson', price: 21.00, imageUrl: 'https://covers.openlibrary.org/b/id/10726075-L.jpg' },
    { title: 'A Little Life', author: 'Hanya Yanagihara', price: 22.50, imageUrl: 'https://covers.openlibrary.org/b/id/10728037-L.jpg' },
    { title: 'Normal People', author: 'Sally Rooney', price: 23.75, imageUrl: 'https://covers.openlibrary.org/b/id/10724635-L.jpg' },
    { title: 'The Immortalists', author: 'Chloe Benjamin', price: 19.25, imageUrl: 'https://covers.openlibrary.org/b/id/10769558-L.jpg' },
    { title: 'The Woman in Cabin 10', author: 'Ruth Ware', price: 20.50, imageUrl: 'https://covers.openlibrary.org/b/id/10757056-L.jpg' },
    { title: 'The Couple Next Door', author: 'Shari Lapena', price: 18.75, imageUrl: 'https://covers.openlibrary.org/b/id/10754834-L.jpg' },
    { title: 'Behind Closed Doors', author: 'B.A. Paris', price: 22.25, imageUrl: 'https://covers.openlibrary.org/b/id/10769383-L.jpg' },
    { title: 'The Girl Before', author: 'JP Delaney', price: 19.75, imageUrl: 'https://covers.openlibrary.org/b/id/10723727-L.jpg' },
    { title: 'The Woman in the Window', author: 'A.J. Finn', price: 16.50, imageUrl: 'https://covers.openlibrary.org/b/id/10568768-L.jpg' },
    { title: 'The Woman in Cabin 10', author: 'Ruth Ware', price: 20.00, imageUrl: 'https://covers.openlibrary.org/b/id/10757056-L.jpg' },
    { title: 'The Couple Next Door', author: 'Shari Lapena', price: 18.25, imageUrl: 'https://covers.openlibrary.org/b/id/10754834-L.jpg' },
    { title: 'The Girl on the Train', author: 'Paula Hawkins', price: 17.75, imageUrl: 'https://covers.openlibrary.org/b/id/10552713-L.jpg' },
    { title: 'Big Little Lies', author: 'Liane Moriarty', price: 19.50, imageUrl: 'https://covers.openlibrary.org/b/id/8572965-L.jpg' },
    { title: 'Little Fires Everywhere', author: 'Celeste Ng', price: 21.00, imageUrl: 'https://covers.openlibrary.org/b/id/10493938-L.jpg' },
    { title: 'Where the Crawdads Sing', author: 'Delia Owens', price: 23.50, imageUrl: 'https://covers.openlibrary.org/b/id/10774539-L.jpg' },
    { title: 'The Night Circus', author: 'Erin Morgenstern', price: 18.25, imageUrl: 'https://covers.openlibrary.org/b/id/8300628-L.jpg' },
    { title: 'The Casual Vacancy', author: 'J.K. Rowling', price: 22.00, imageUrl: 'https://covers.openlibrary.org/b/id/8273438-L.jpg' },
    { title: 'The Underground Railroad', author: 'Colson Whitehead', price: 19.75, imageUrl: 'https://covers.openlibrary.org/b/id/10722643-L.jpg' },
    { title: 'Circe', author: 'Madeline Miller', price: 20.00, imageUrl: 'https://covers.openlibrary.org/b/id/8236821-L.jpg' },
    { title: 'The Silent Patient', author: 'Alex Michaelides', price: 22.50, imageUrl: 'https://covers.openlibrary.org/b/id/10729079-L.jpg' },
    { title: 'Before We Were Strangers', author: 'Renée Carlino', price: 17.00, imageUrl: 'https://covers.openlibrary.org/b/id/10771173-L.jpg' },
    { title: 'The Tattooist of Auschwitz', author: 'Heather Morris', price: 18.75, imageUrl: 'https://covers.openlibrary.org/b/id/10727828-L.jpg' },
    { title: 'The Light We Lost', author: 'Jill Santopolo', price: 20.25, imageUrl: 'https://covers.openlibrary.org/b/id/10752856-L.jpg' },
    { title: 'The Paris Library', author: 'Janet Skeslien Charles', price: 21.00, imageUrl: 'https://covers.openlibrary.org/b/id/10727022-L.jpg' },
    { title: 'The Orphan Masters Son', author: 'Adam Johnson', price: 22.50, imageUrl: 'https://covers.openlibrary.org/b/id/10726075-L.jpg' },
    { title: 'A Little Life', author: 'Hanya Yanagihara', price: 24.00, imageUrl: 'https://covers.openlibrary.org/b/id/10728037-L.jpg' },
    { title: 'Normal People', author: 'Sally Rooney', price: 23.75, imageUrl: 'https://covers.openlibrary.org/b/id/10724635-L.jpg' },
    { title: 'The Immortalists', author: 'Chloe Benjamin', price: 19.50, imageUrl: 'https://covers.openlibrary.org/b/id/10769558-L.jpg' },
    { title: 'The Woman in Cabin 10', author: 'Ruth Ware', price: 18.75, imageUrl: 'https://covers.openlibrary.org/b/id/10757056-L.jpg' },
    { title: 'The Couple Next Door', author: 'Shari Lapena', price: 20.00, imageUrl: 'https://covers.openlibrary.org/b/id/10754834-L.jpg' },
    { title: 'Behind Closed Doors', author: 'B.A. Paris', price: 21.50, imageUrl: 'https://covers.openlibrary.org/b/id/10769383-L.jpg' },
    { title: 'The Girl Before', author: 'JP Delaney', price: 22.25, imageUrl: 'https://covers.openlibrary.org/b/id/10723727-L.jpg' },
    { title: 'The Woman in the Window', author: 'A.J. Finn', price: 23.00, imageUrl: 'https://covers.openlibrary.org/b/id/10568768-L.jpg' },
    { title: 'The Girl on the Train', author: 'Paula Hawkins', price: 16.75, imageUrl: 'https://covers.openlibrary.org/b/id/10552713-L.jpg' },
    { title: 'The Night Circus', author: 'Erin Morgenstern', price: 20.25, imageUrl: 'https://covers.openlibrary.org/b/id/8300628-L.jpg' },
    { title: 'The Casual Vacancy', author: 'J.K. Rowling', price: 22.00, imageUrl: 'https://covers.openlibrary.org/b/id/8273438-L.jpg' },
    { title: 'The Underground Railroad', author: 'Colson Whitehead', price: 24.00, imageUrl: 'https://covers.openlibrary.org/b/id/10722643-L.jpg' },
    { title: 'Circe', author: 'Madeline Miller', price: 23.50, imageUrl: 'https://covers.openlibrary.org/b/id/8236821-L.jpg' },
    { title: 'The Silent Patient', author: 'Alex Michaelides', price: 21.00, imageUrl: 'https://covers.openlibrary.org/b/id/10729079-L.jpg' },
    { title: 'Before We Were Strangers', author: 'Renée Carlino', price: 22.50, imageUrl: 'https://covers.openlibrary.org/b/id/10771173-L.jpg' },
    { title: 'The Tattooist of Auschwitz', author: 'Heather Morris', price: 19.75, imageUrl: 'https://covers.openlibrary.org/b/id/10727828-L.jpg' },
    { title: 'The Light We Lost', author: 'Jill Santopolo', price: 20.50, imageUrl: 'https://covers.openlibrary.org/b/id/10752856-L.jpg' },
    { title: 'The Paris Library', author: 'Janet Skeslien Charles', price: 22.00, imageUrl: 'https://covers.openlibrary.org/b/id/10727022-L.jpg' },
    { title: 'The Orphan Masters Son', author: 'Adam Johnson', price: 23.75, imageUrl: 'https://covers.openlibrary.org/b/id/10726075-L.jpg' },
    { title: 'A Little Life', author: 'Hanya Yanagihara', price: 24.00, imageUrl: 'https://covers.openlibrary.org/b/id/10728037-L.jpg' },
    { title: 'Normal People', author: 'Sally Rooney', price: 21.50, imageUrl: 'https://covers.openlibrary.org/b/id/10724635-L.jpg' },
    { title: 'The Immortalists', author: 'Chloe Benjamin', price: 20.00, imageUrl: 'https://covers.openlibrary.org/b/id/10769558-L.jpg' }
  ];

  constructor(private router: Router) { }

  ngOnInit(): void {
    this.router.events.subscribe(() => {
      this.isHomeRoute = this.router.url === '/dashboard/home';
      this.ismaintainRoute = this.router.url === '/dashboard/maintainence';
      this.isbookRoute = this.router.url === '/dashboard/book';
    });
  }
}